package ru.privatenull.pnrelog.api.action;

public enum ActionTrigger {
    COMBAT_START_ATTACKER,
    COMBAT_START_TARGET,
    COMBAT_JOIN,
    COMBAT_MERGE,
    COMBAT_CONTINUE,
    COMBAT_TICK,
    COMBAT_END,
    COMBAT_LOGOUT,
    COMBAT_KICK,
    COMMAND_BLOCKED,
    PLAYER_COMMAND_BLOCKED,
    TELEPORT_BLOCKED,
    ELYTRA_BLOCKED,
    ITEM_COOLDOWN,
    ITEM_PREVENTED,
    ITEM_COOLDOWN_ENDED,
    ITEM_HELD
}
